"""
Master Synthesizer Agent
========================
Aggregates the individual drafts produced by the parallel expert agents.
Also acts as the reviser if the Critic Agent rejects the draft.
"""

from langchain_groq import ChatGroq
from config import LLM_SYNTHESIZER
from rag.pipeline import retrieve_rag_context

def node_master_synthesizer(state: dict) -> dict:
    print("\n" + "=" * 60)
    print(">>> MASTER SYNTHESIZER: Aggregating Expert Drafts")
    print("=" * 60)

    expert_drafts = state.get("expert_drafts", [])
    critic_feedback = state.get("critic_feedback", "")
    query = state.get("user_query", "")
    
    if not expert_drafts:
        return {"final_draft": "No expert drafts generated."}
    
    # Combine drafts
    combined_drafts_text = ""
    for idx, ed in enumerate(expert_drafts):
        domain = ed.get("domain", "Unknown Domain")
        draft = ed.get("draft", "")
        combined_drafts_text += f"\n--- EXPERT DRAFT {idx+1} ({domain}) ---\n{draft}\n"
        
    rag_context = state.get("rag_context", "")
    print(f"    [+] Loaded {len(rag_context)} bytes of RAG context.")
        
    prompt = f"""You are the Master Legal Synthesizer.
Your job is to read the individual legal opinions generated by our domain experts, 
reference the fundamental Constitutional/Textbook principles retrieved via RAG,
and combine everything into a single, cohesive, flawless Legal Memorandum.

=== USER QUERY ===
{query}

{rag_context}

=== EXPERT OPINIONS TO AGGREGATE ===
{combined_drafts_text}
"""
    
    if critic_feedback:
        print(f"    [!] Applying Critic Feedback for Revision {state.get('revision_count', 0) + 1}")
        prompt += f"""
=== CRITIC FEEDBACK (REVISION REQUIRED) ===
The previous draft was REJECTED by the Senior Legal Critic for the following reasons:
{critic_feedback}

You MUST address this feedback and fix the errors in your new combined draft.
"""
    
    prompt += """
=== INSTRUCTIONS ===
1. Create a unified, highly professional legal memorandum.
2. If multiple domains are involved, create clear sections for each domain.
3. Ensure the tone is authoritative and cohesive.
4. Do NOT hallucinate cases; only cite what the experts provided.
5. Provide a final comprehensive Executive Summary and Strategy at the end.
"""

    try:
        llm = ChatGroq(model=LLM_SYNTHESIZER, temperature=0.2)
        response = llm.invoke(prompt)
        final_text = response.content
    except Exception as e:
        print(f"    [!] Synthesizer LLM error: {e}")
        final_text = "[ERROR] Master synthesis failed."
        
    print("    Master Draft complete.")
    return {"final_draft": final_text}
